import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Section } from '../components/layout'

import Image from 'next/image'
import { Button } from '../components/form'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'

const Car: NextPage = () => { 

    const [cars, setCars] = useState([])

    const { query } = useRouter()

    const id = query.id?.toString()

    axios.get('http://localhost:8080/cars/?id=' + id, {
        headers: {
            'Authorization': 'Bearer ' + localStorage.getItem('token')
        }
    }).then(response => {
        setCars(response.data)
    }).catch(error => {
        console.log(error)
    });

  return (
    <>
      <Head>
        <title>DevCar - car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Section>
        <Box>
            <Box width="60vh" 
                flexDirection='column'>
                <Box>
                    <strong>{cars.name} - {cars.model}</strong>
                </Box>
                <Image src="https://picsum.photos/200/300?random=1" alt="car" width={300} height={300} />
            </Box>
            <Box width="50vh" flexDirection='column'>
                <h2>Descrição:</h2>
                <p>
                    {cars.description}
                </p>
                <h2>Marca:</h2>
                <p>
                    {cars.brand}
                </p>

                <h2>Preço:</h2>
                <h1>15999.08998</h1>
                <Button>Comprar</Button>
            </Box>
        </Box>
      </Section>
    </>
  )
}

export default Car
