import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Section } from '../components/layout'

import Image from 'next/image'
import { Button, Form, Input } from '../components/form'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'

const Signin: NextPage = () => { 
  return (
    <>
      <Head>
        <title>DevCar - Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Section>
        <Box flexDirection='column' justifyContent='center'>
            <h1>Sign in</h1>
            <Form>
                <label htmlFor="email">Email</label>
                <Input placeholder="email" type="email" />
                <label htmlFor="password">Password</label>
                <Input placeholder="password" type="password" />
                <Button>Sign in</Button>
            </Form>
        </Box>
      </Section>
    </>
  )
}

export default Signin
