import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Section } from '../components/layout'

import Image from 'next/image'
import { Button, Form, Input } from '../components/form'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'
import { signup, login } from '../api/login'

const Signup: NextPage = () => { 

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [name, setName] = useState('')

  const router = useRouter()

  const handleSubmit = (e: any) => {
    e.preventDefault()
    signup(email, password, name).then(({ data }) => {
      login(email, password).then(({ data }) => {
        localStorage.setItem('token', data)
        router.push('/admin')
      })
    }).catch(err => console.log(err))
  }

  return (
    <>
      <Head>
        <title>DevCar - Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Section>
        <Box flexDirection='column' justifyContent='center'>
            <h1>Sign up</h1>
            <Form>
                <label htmlFor="name">Name</label>
                <Input onChange={(e) => setName(e.target.value)} placeholder="name" type="text" />
                <label htmlFor="email">Email</label>
                <Input onChange={(e) => setEmail(e.target.value)} placeholder="email" type="email" />
                <label htmlFor="password">Password</label>
                <Input onChange={(e) => setPassword(e.target.value)} placeholder="password" type="password" />
            </Form>
            <Button onClick={handleSubmit}>Sign up</Button>
        </Box>
      </Section>
    </>
  )
}

export default Signup
