import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Section } from '../components/layout'

import Image from 'next/image'
import { Button, Form, Input } from '../components/form'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'

const Signin: NextPage = () => { 

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const router = useRouter()

  const handleSubmit = (e: any) => {
    e.preventDefault()

    console.log(email, password)

    axios.post( process.env.base_url + 'login', {
      email,
      password
    }).then(response => {
      localStorage.setItem('token', response.data)
      router.push('/admin')
    }).catch(error => {
      console.log(error)
    })
  }

  return (
    <>
      <Head>
        <title>DevCar - Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Section>
        <Box flexDirection='column' justifyContent='center'>
            <h1>Sign in</h1>
            <Form>
                <label htmlFor="email">Email</label>
                <Input onChange={(e) => setEmail(e.target.value)} placeholder="email" type="email" />
                <label htmlFor="password">Password</label>
                <Input onChange={(e) => setPassword(e.target.value)} placeholder="password" type="password" />
                <Button onClick={handleSubmit}>Sign in</Button>
            </Form>
        </Box>
      </Section>
    </>
  )
}

export default Signin
